Adjust batch_size for content pre-migration part
pulp/pulp-2to3-migration pull request #323
Opened 2021-02-23 16:07 UTC by goosemania

It can take a while to process content, especially errata,
so a batch size nees to be smaller for cursor not to timeout.

[noissue]

2021-02-23 16:38 UTC, dralley approved these changes

2021-02-23 16:40 UTC, goosemania commented
@ggainey , please merge this one if/when you confirm that it helped.

2021-02-24 17:55 UTC, ggainey requested changes

2021-02-24 17:55 UTC, ggainey commented on pulp_2to3_migration/app/pre_migration.py
> +    batch_size = 200
dogfood-clone experience suggests that a conservative 100 is better

2021-02-24 18:05 UTC, ggainey approved these changes
Perfect - let's see how this does for us!

2021-02-24 18:21 UTC, merged