Add a note about migrating to a FIPS machine.
pulp/pulp-2to3-migration pull request #445
Opened 2021-08-31 21:56 UTC by goosemania

closes #7992
https://pulp.plan.io/issues/7992

2021-08-31 23:13 UTC, ggainey requested changes
Just some minor wordsmithing!

2021-08-31 23:13 UTC, ggainey commented on docs/configuration.rst
> +    If you'd like to run Pulp 3 on a machine where FIPS is enabled, you would need to patch
^would^will

2021-08-31 23:13 UTC, ggainey commented on docs/configuration.rst
> +    patches will go away when Django project starts supporting FIPS mode.
"...starts supporting FIPS mode (see https://code.djangoproject.com/ticket/28401 for details)."

2021-09-01 18:47 UTC, goosemania commented
@ggainey , ready for re-review

2021-09-01 18:52 UTC, ggainey approved these changes
lg2m!

2021-09-01 18:57 UTC, merged